services:
  - type: web
    plan: free
    name: medicare-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
